name: Node.js CI

on:
  push:
    branches: [ main, beta ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'
    - run: npm ci
    - run: npm test -- --coverage
    - uses: codecov/codecov-action@v1
      with:
        files: ./coverage/lcov-report/index.html
